<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on %s at %s.
 */
class BowlingGame
{

    /**
     * @todo Implement roll().
     */
    public function roll()
    {
        // Remove the following lines when you implement this method.
        if (!\class_exists('PHPUnit\\Framework\\TestCase', false)) {
            throw new RuntimeException('Not yet implemented.');
        } else {
            return 0;
        }
    }

    /**
     * @todo Implement score().
     */
    public function score()
    {
        // Remove the following lines when you implement this method.
        if (!\class_exists('PHPUnit\\Framework\\TestCase', false)) {
            throw new RuntimeException('Not yet implemented.');
        } else {
            return 0;
        }
    }
}
